"""Cloud logging and monitoring security scanner."""


LOGGING_RULES = [
    {
        "id": "LOG-001",
        "name": "CloudTrail / Audit logging enabled",
        "description": "Cloud audit logging should be enabled in all regions",
        "severity": "Critical",
        "check_field": "audit_logging_enabled",
        "expected": True,
        "remediation": "Enable audit logging (CloudTrail/Cloud Audit Logs) across all regions.",
        "cis_benchmark": "CIS 2.1",
    },
    {
        "id": "LOG-002",
        "name": "Log file integrity validation",
        "description": "Log file integrity validation should be enabled",
        "severity": "High",
        "check_field": "log_integrity_validation",
        "expected": True,
        "remediation": "Enable log file digest/integrity validation to detect tampering.",
        "cis_benchmark": "CIS 2.2",
    },
    {
        "id": "LOG-003",
        "name": "Logs encrypted at rest",
        "description": "Log storage should be encrypted with KMS",
        "severity": "High",
        "check_field": "logs_encrypted",
        "expected": True,
        "remediation": "Enable KMS encryption for log storage buckets.",
        "cis_benchmark": "CIS 2.3",
    },
    {
        "id": "LOG-004",
        "name": "Log retention period",
        "description": "Logs should be retained for at least 365 days",
        "severity": "Medium",
        "check_field": "log_retention_days",
        "expected_min": 365,
        "remediation": "Set log retention to at least 365 days for compliance.",
        "cis_benchmark": "CIS 2.4",
    },
    {
        "id": "LOG-005",
        "name": "Unauthorized API call alerts",
        "description": "Alerts should be configured for unauthorized API calls",
        "severity": "High",
        "check_field": "alert_unauthorized_api",
        "expected": True,
        "remediation": "Create metric filters and alarms for unauthorized API calls.",
        "cis_benchmark": "CIS 2.5",
    },
    {
        "id": "LOG-006",
        "name": "Root account usage alerts",
        "description": "Alerts should be configured for root account usage",
        "severity": "Critical",
        "check_field": "alert_root_usage",
        "expected": True,
        "remediation": "Create alerts to notify when root account is used.",
        "cis_benchmark": "CIS 2.6",
    },
    {
        "id": "LOG-007",
        "name": "IAM policy change alerts",
        "description": "Alerts should be configured for IAM policy changes",
        "severity": "High",
        "check_field": "alert_iam_changes",
        "expected": True,
        "remediation": "Create alerts for IAM policy modifications.",
        "cis_benchmark": "CIS 2.7",
    },
    {
        "id": "LOG-008",
        "name": "Security group change alerts",
        "description": "Alerts should be configured for security group changes",
        "severity": "High",
        "check_field": "alert_sg_changes",
        "expected": True,
        "remediation": "Create alerts for security group rule modifications.",
        "cis_benchmark": "CIS 2.8",
    },
    {
        "id": "LOG-009",
        "name": "NACL change alerts",
        "description": "Alerts for network ACL changes",
        "severity": "Medium",
        "check_field": "alert_nacl_changes",
        "expected": True,
        "remediation": "Create alerts for NACL modifications.",
        "cis_benchmark": "CIS 2.9",
    },
    {
        "id": "LOG-010",
        "name": "Config changes recording",
        "description": "Resource configuration changes should be recorded",
        "severity": "High",
        "check_field": "config_recording_enabled",
        "expected": True,
        "remediation": "Enable configuration recording (AWS Config / GCP Asset Inventory).",
        "cis_benchmark": "CIS 2.10",
    },
]
